config/routes.rb
WwqiPlatform::Application.routes.draw do
  #devise_for :admin_users, ActiveAdmin::Devise.config
  get "autocomplete/users"

  get '/activity/activity_data'

  devise_for :users, controllers: { registrations: 'registrations' }
  devise_scope :user do
    get '/users/sign_up/:token' => 'registrations#new'
  end

  resources :users do
    resources :notifications
  end

  resources :posts, controller: :threads, path: :threads do
    resources :comments
    resources :followings
  end

  resources :researches do
    resources :comments
    resources :followings
  end

  resources :contributions do
    resources :comments
    resources :followings
  end

  resources :corrections

  resources :biographies

  resources :transcriptions, :translations, controller: :contributions

  match "/admin" => "admin/dashboard#index"
  match "/me" => "profile#show", :as => 'my_profile'
  match "/me/notifications" => "profile#notifications", :as => 'my_notifications'

  root :to => 'site#index'

  ActiveAdmin.routes(self)
end

app/views/partials/_collaborator_fields.html.haml
.nested-fields
  .collaborator-group
    = f.input :term, label: false, placeholder: "e.g. ali@utoronto.ca or Ali Diba"
    = f.input :user_id, label: false, as: :hidden
  .links-remove
    = link_to_remove_association '', f, class: 'icon-minus-circle'

app/views/partials/_comments.html.haml
- klass_name = resource.model.class.to_s.downcase
- parent_class = resource.model.class.lookup_ancestors.last.to_s
.comments
  - resource.comments.each do |c|
    .comment
      %a{href: "#c#{c.id}"}
      .item-image.pull-left
        = image_tag avatar_url(c.user)
      .item-content.pull-left
        .item-created.full-width
          = "#{c.header} #{c.created_ago}"
        .item-details
        .wysiwyg
          != c.details
        .item-bottom
          - unless c.items.empty?
            %ul.thumbnails
              - c.items.each do |i|
                %li.span1
                  .thumbnail{ title: "#{i.name}" }
                    = image_tag i.thumbnail, size: "50x50", "data-src" => "holder.js/50x50"
          -# check the parent class and set the right path for editing a comment
          - edit_path_arg = parent_class == 'Post' ? edit_post_comment_path(resource, c) : edit_contribution_comment_path(resource, c)
          = link_to "edit", edit_path_arg, {class: ''} if current_user == c.user
.comment-box
  - if user_signed_in?
    .item-image.pull-left
      = image_tag avatar_url(current_user)
    .item-content.pull-right
    -# check the paren class and set the right url for a comment form
    - new_path_arg = parent_class == 'Post' ? post_comments_path(resource) : contribution_comments_path(resource)
    = simple_form_for Comment.new, url: new_path_arg do |f|
      = f.input :details, label: t("#{klass_name}.comment_label"), input_html: { class: 'whsihtml5-sandbox' }
      = f.submit t("#{klass_name}.submit"), { class: "btn pull-right submit-button", id: "comment-submit-button" }
  - else
    .black-box
      %p=raw t('sign_in_to_comment', type: klass_name, link: link_to(t('sign_in').downcase, root_path(anchor: 'sign-in')), scope: 'posts.show')

:coffeescript
  $( ->
    $('.thumbnail').mouseover (event) ->
      $(this).tooltip('show')
  )

app/views/partials/_footer.html.haml
.container
  #footer.row-fluid
    .credits
      = link_to 'http://www.roshan-institute.org/', target: '_blank' do
        = image_tag 'roshan-logo.png', class: 'roshan-logo'
      %p
        This Research Platform has become possible in part through a grant by Roshan Cultural Heritage Institute.

app/views/partials/_item_autocomplete.html.haml
:coffeescript
  $ ->
    -# This javascript is for handling the url parameter from qajar women site.
    params = window.location.search.match(/(accession_no=\S+)/)
    if params
      accession_no = params[1].split('=')[1]

      $('button[value="true"][name="item_related"]').trigger('click')
      $('#items').find('input[id$="_search"]').autocomplete('search', accession_no)
      $('#items').find('input[id$="_search"]').on('autocompleteopen', (event, ui) ->
        $(".ui-menu-item:first").trigger('click'))

app/views/partials/_item_fields.html.haml
.nested-fields.row-fluid
  .item-group
    .item-image.pull-left
      = image_tag 'flag.png'
    = f.input :search, label: false, placeholder: 'e.g. tin or 1266A16', input_html: { style: 'width:20em', style: 'margin-right:0.5em' }
    = f.input :url, :as => :hidden
    = f.input :thumbnail, :as => :hidden
    = f.input :accession_no, :as => :hidden
    = f.input :name, :as => :hidden
  .links-remove
    = link_to_remove_association '', f, class: 'icon-minus-circle'

app/views/partials/_terms_dialog.html.haml
#dialog.terms-dialog
  .language-select-dialog
    .select-farsi-dialog فارسی
    .select-english-dialog english
  .terms-english-dialog
    .horiz-line
    .agree
      %p Please note that by creating a Username and Password, you are agreeing to the points spelled out in our User Policy. Please read the User Policy below and confirm your acceptance before proceeding. Thank you.
    .horiz-line
    %h3 User Policy
    %p This Platform is administered by WWQI editors. We reserve the right to edit or remove any posting that is not related to the purpose of this website, or that is otherwise inappropriate.
    %h3 Use of Postings &mdash; Copyrights
    %p You agree that WWQI may use copy, edit and use your posted Corrections, and biographical and historical information that you post in Questions and Discussions Threads,  to revise its pages. Where applicable, such information will be linked back to the related Thread for all viewers to be able to track your contribution.
    %p Your postings to Research-in-Progress and Contributions – Transcription, Translations, Biographies – are your intellectual property and you have the ability to select with whom you share them. Should WWQI wish to use any of these materials on our public site (www.qajarwomen.org), we will contact you and ask for your written permission.
    %p As a user, you are required to respect other users’ copyrights to their postings and to follow standard referencing protocols when you use any such material.
    %p.no-margin If you believe that your copyrighted work is being infringed by any material posted in the WWQI Research Platform, please visit
    %span
      %a{href: 'http://www.harvard.edu/reporting-copyright-infringements', tabindex: '-1'} harvard.edu/reporting-copyright-infringements
    %span
      %p and follow the procedures set out there.

    %h3 Privacy
    %p The workings of our applications by default collect certain information when you register as a user and log in.

    %h3 What do we use your information for?
    %p We use your IP address to help diagnose problems with our server and to administer our website by identifying which parts of our site are most heavily used. We do not link IP addresses to anything personally identifiable. This means that when user sessions are tracked, the users will remain anonymous.
    %p The email address you provide may be used to send you information, respond to inquiries, and/or other requests or questions.
    %p We may also provide your information to third parties in circumstances where Harvard University regulations require.

    %h3 Device Information Collected By Us
    %p We may collect non-personal information about the computer, mobile device or other device you use to access our site, such as IP address, geolocation information, unique device identifiers, browser type, browser language or other information of this nature. We use this information in an aggregate fashion to track access to the site. At no time do we disclose site usage by individual IP addresses. Web server logs are retained on a temporary basis and then deleted from our systems.

    %h3 Cookies
    %p Cookies are small files that are stored on your computer (unless you block them). We use cookies to understand and save your preferences for future visits and compile aggregate data about site traffic and site interaction so that we can offer better site experiences and tools in the future. We may contract with third-party service providers to assist us in better understanding our site visitors. These service providers are not permitted to use the information collected on our behalf except to help us conduct and improve our site.

    %h3 Third-Party Cookies
    %p Cookies may be set by an organization other than WWQI. These “third-party cookies” may, for example, originate from websites such as Twitter, Facebook, Google Plus or other social media services for which our site has implemented “plug-ins.” Since the cookie policies of these sites change over time, you should determine their policies by visiting the privacy policy pages of these sites directly.
    %p You may disable cookies through your individual browser options. If you would like to learn more about cookies please refer to the following website:
    %span
      %a{href: "http://www.allaboutcookies.org", tabindex: '-1'}allaboutcookies.org
    %h3 Links to Third-Party Websites
    %p We may provide hyperlinks to third-party websites as a convenience to users of WWQI. WWQI does not control third-party websites and is not responsible for the contents or privacy practices of any linked-to, third-party websites or any hyperlink in a linked-to website.

    %h3 Email Policy
    %p We will not share, sell, rent, swap or authorize any third party to use your email address.

    %h3 Information Protection
    %p To prevent unauthorized access, maintain data accuracy and ensure the appropriate use of information that has been gathered about you, we have taken commercially reasonable steps to protect the information. However, no method of transmission over the Internet, or method of electronic storage, is 100% secure.

    %h3 Changes to Our Policies
    %p We may amend our User Policy or our Privacy Policy from time to time. Any such changes will be posted on this page. The effective date of this policy is April 1st, 2013.
    %button.btn.close-dialog{type: "button", tabindex: '-1'} Close

  .terms-farsi-dialog
    .horiz-line
    .agree
      %p لطفاً توجه کنید که ایجاد نام کاربری و رمز ورود به معنای توافق شما در مورد رعایت مقررات کاربران این سایت است. لطفاً پیش از اینکه ادامه دهید این مقررات را بخوانید و موافقت خود را با آنها اعلام کنید. متشکریم.
    .horiz-line
    %h3 مقررات کاربری
    %p مدیریت این پژوهشگاه را ویراستاران «دنیای زنان در عصر قاجار» بر عهده دارند، و می توانند در صورت لزوم مطالب را ویرایش و هر گونه مطلب نامناسب و یا نامربوط با اهداف این وبسایت را حذف کنند.

    %h3 استفاده از مطالب؛ حقوق مؤلف
    %p «دنیای زنان در عصر قاجار» اجازه دارد برای ویرایش صفحات این وبسایت از اصلاحات مربوط به اطلاعات تاریخی و زندگی‌نامه‌ای که شما در بخش سؤالات و بحث‌ها می‌نویسید استفاده کند. در صورت امکان، این اطلاعات به سؤالات و بحث‌های مربوطه پیوند خواهد خورد تا تمام کاربران بتوانند مشارکت شما را پی‌گیری کنند.
    %p حق تألیف مطالب نوشته شما در بخش «تحقیق در حال انجام» و «مشارکت» -- استنساخ، ترجمه، زندگی‌نامه -- متعلق به شماست و شما می‌توانید انتخاب کنید که این‌ اطلاعات را با چه کسانی به اشتراک بگذارید. در صورتی که «دنیای زنان در عصر قاجار» بخواهد از مطالب شما در وبسایت خود (www.qajarwomen.org) استفاده کند، از شما درخواست اجازه‌ کتبی خواهیم کرد.
    %p به عنوان کاربر شما موظفید حقوق تألیف دیگر کاربران را رعایت کنید و در صورت استفاده از مطالب ایشان منبع مورد استفاده را ذکر کنید.
    %p اگر فکر می‌کنید حق تألیف شما نادیده گرفته شده است می توانید به صفحه www.harvard.edu/reporting-copyright-infringements  مراجعه و مراحل ذکر شده را دنبال کنید.

    %h3 حریم شخصی
    %p برنامه‌های کاربردی ما برخی از اطلاعات شما را که هنگام ثبت نام در اختیار می گذارید نگه می دارد.

    %h3 از این اطلاعات شما چه استفاده ای می‌شود؟
    %p از نشانی آی پی شما برای تشخیص مشکلات شبکه‌ استفاده شود. همچنین با این نشانی می توانیم تشخیص دهیم از کدام بخش وبسایت بیشتر استفاده می‌شود که این امر به مدیریت آن کمک می کند. در این فرآیند اطلاعات شخصی کاربران پوشیده می ماند و نشانی آی پی به اطلاعات شخصی مرتبط نمی شود.
    %p نشانی ایمیلی که در اختیار ما می‌گذارید ممکن است برای فرستادن اطلاعات،‌ پاسخ به پرسشها، ویا دیگر موارد مشابه استفاده شود.
    %p همچنین بنا بر قوانین دانشگاه هاروارد، در صورت لزوم، اطلاعات شما در اختیار شخص ثالث قرار خواهد گرفت.

    %h3 اطلاعاتی که ما از دستگاه جمع آوری می‌کنیم
    %p برخی اطلاعات غیرشخصی به صورت انبوه جمع آوری می شود تا بتوانیم راههای دسترسی به وبسایت را بررسی کنیم. این اطلاعات مربوط به نوع رایانه، تلفن همراه، و یا وسایل ارتباطی دیگر می باشد و اطلاعاتی در مورد نشانی آی پی، محل جغرافیایی، شناسه‌های یگانه دستگاه‌، نوع مرورگر، و زبان مرورگر را در اختیار ما قرار می دهد. این اطلاعات بهیچوجه هویت کاربر را آشکار نخواهد کرد و به دلیل موقتی بودن پس از استفاده از سیستم پاک خواهد شد.

    %h3 کوکی ها
    %p کوکی ها فایل‌های کوچکی هستند که روی کامپیوتر شما ذخیره می‌شوند (مگر اینکه راه ورودشان را مسدود کنید). این کوکی ها به ما کمک می کنند تا علاقه مندی های شما را در بازدید از سایت دنبال کنیم و در نتیجه ابزارهای موجود را بهبود بخشیم. ممکن است از واحدهای خدماتی دیگر کمک بگیریم تا درک بهتری از نحوه استفاده کاربرانمان پیدا کنیم. این واحدها تنها در مواردی که به بهبود سایت کمک کند می توانند از این اطلاعات استفاده کنند.

    %h3 کوکی های سایت‌های دیگر
    %p ممکن است سایتهایی نظیر توییتر، فیس بوک، گوگل پلاس، یا دیگر شبکه‌های اجتماعی مجازی که وبسایت ما با پلاگین آن‌ها پیوند دارد کوکی هایی کار بگذارند. مقررات کوکی های این سایت‌ها در طول زمان تغییر می کند. برای دانستن این مقررات به صفحات مربوط به مقررات حقوق شخصی این وبسایت ها مراجعه کنید.
    %p شما می‌توانید این کوکی ها را از طریق انتخاب‌های شخصی مرورگرتان غیر فعال کنید. اگر مایلید درباره کوکی ها بیشتر بدانید به این وبسایت رجوع کنید: www.allaboutcookies.org

    %h3 پیوند به سایت‌های دیگر
    %p ممکن است برای تسهیل استفاده کاربرهای «دنیای زنان در عصر قاجار»، سایتمان را به وبسایت های دیگر پیوند دهیم، ولی مسؤولیت محتوا و شیوه کار و مقررات آنها-- و یا دیگر وبسایت‌هایی که آنها به سایت خود پیوند داده‌اند -- بر عهده سایت ما نیست.

    %h3 خط مشی نامه الکترونیکی
    %p آدرس ایمیل شما به هیچ عنوان و دلیل در اختیار شخص دیگری قرار نخواهد گرفت.

    %h3 محافظت از اطلاعات
    %p ما برای جلوگیری از دسترسی بدون اجازه، حفظ دقت اطلاعات، و اطمینان از استفاده‌ مناسب از اطلاعاتی که درباره شما جمع شده است، اقدامات موجود و معقول را انجام می دهیم. با این حال، هیچ روش انتقال در شبکه اینترنتی و یا شیوه ذخیره الکترونیکی صد در صد امن نیست.

    %h3 تغییر مقررات ما
    %p ممکن است مقررات مربوط به حریم شخصی و یا مقررات مربوط به کاربری را هر از گاهی تغییر دهیم. هرگونه تغییری از این دست در این صفحه به اطلاع خواهد رسید. تاریخ آغاز اجرای مقررات کنونی اول آوریل ۲۰۱۳ است.
    %button.btn.close-dialog{type: "button"} Close

app/views/partials/_upload_fields.html.haml
.nested-fields.row-fluid
  = f.input :content, label: false, input_html: { class: 'upload'}
  = f.input :content_cache, as: :hidden
  .dummyfile
    %a.fileselectbutton.btn Choose...
    %input.filename{type: 'text', name: 'filename', value: f.object["content"]}
  .links-remove
    = link_to_remove_association '', f, :class => 'icon-minus-circle'
  #alert-message

app/views/partials/_user_registration.html.haml
#registration
  .sign-in-header.english
    %h2 Sign Up
    %p Start using the research platform today.
  .sign-in-header.farsi
    %h2 ثبت نام
    %p اگر بار اولی است که وارد این پژوهشگاه می‌شوید، از اینجا شروع کنید.
    %span لطفا توجه کنید که نام و نام خانوادگی باید به حروف لاتین باشد. برای رمز ورود می توانید از حروف و اعداد لاتین استفاده کنید.
  .horiz-line
  = simple_form_for resource, url: user_registration_path, remote: true do |f|
    = f.input :first_name, input_html: { class: 'text-input'}
    = f.input :last_name, input_html: { class: 'text-input'}
    = f.input :email, input_html: { id: "sign_up_user_email", class: "text-input" }
    = f.input :password, input_html: { id: "sign_up_user_password", class: "text-input" }
    = f.input :password_confirmation, input_html: { class: "text-input" }
    = f.input :token, as: :hidden, label: false, input_html: { value: "#{params[:token]}"}
    .terms
      #legal_terms
        %a{href: 'javascript:void(0)'}
          %span Please read and accept the terms and conditions.
        %span.icon-right-open-mini
      #legal_terms_farsi
        %a{href: 'javascript:void(0)'}
          %span لطفأ مقررات کاربری را مطالعه کرده و موافقت خود را اعلام کنید
        %span.icon-right-open-mini
      = render 'partials/terms_dialog'
      .checkbox
        = f.check_box :terms
        = f.label :terms do
          I accept / می پذیرم
          %span
        - if resource.errors[:terms].any?
          %span.error= resource.errors[:terms].to_sentence
    = f.button :submit, 'Sign Up', { class: 'btn' }
  .horiz-line-thick.hidden-desktop.hidden-tablet

app/views/partials/_user_session.html.haml
#sign-in
  .sign-in-header.english
    %h2 Sign In
    %p Already a member? Sign in below.
  .sign-in-header.farsi
    %h2 ورود به سایت
    %p اگر ایمیل و رمز ورود دارید، از اینجا وارد شوید.
  .horiz-line
  = simple_form_for "user", url: user_session_path do |f|
    = f.input :email, input_html: { class: "text-input" }
    = f.input :password, input_html: { class: "text-input" }
    = f.button :submit, "Sign In", { class: "btn" }
  = render 'devise/shared/forgot_password'