config/routes.rb
WwqiPlatform::Application.routes.draw do
  #devise_for :admin_users, ActiveAdmin::Devise.config
  get "autocomplete/users"

  get '/activity/activity_data'

  devise_for :users, controllers: { registrations: 'registrations' }
  devise_scope :user do
    get '/users/sign_up/:token' => 'registrations#new'
  end

  resources :users do
    resources :notifications
  end

  resources :posts, controller: :threads, path: :threads do
    resources :comments
    resources :followings
  end

  resources :researches do
    resources :comments
    resources :followings
  end

  resources :contributions do
    resources :comments
    resources :followings
  end

  resources :corrections

  resources :biographies

  resources :transcriptions, :translations, controller: :contributions

  match "/admin" => "admin/dashboard#index"
  match "/me" => "profile#show", :as => 'my_profile'
  match "/me/notifications" => "profile#notifications", :as => 'my_notifications'

  root :to => 'site#index'

  ActiveAdmin.routes(self)
end

app/models/contribution.rb
class Contribution < ActiveRecord::Base
  include AssociateItems

  paginates_per 5

  attr_accessible :details, :uploads_attributes, :item_relation_attributes,
                  :creator_id, :type, :item_attributes, :person_url, :person_name

  has_one :item_relation, as: :itemable, dependent: :destroy
  has_one :item, through: :item_relation
  accepts_nested_attributes_for :item_relation

  belongs_to :creator, class_name: 'User'
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :uploads, as: :uploadable, dependent: :destroy
  has_many :followings, as: :followable, dependent: :destroy
  has_many :followers, through: :followings, class_name: :User

  validates :details, presence: true
  validates :creator_id, :presence => true, :unless => Proc.new {|contribution| contribution.type == "Correction"}

  accepts_nested_attributes_for :uploads, allow_destroy: true, reject_if: :all_blank

  search_methods :user_fullname_contains

  scope :user_fullname_contains, lambda { |str|
    User.joins(:creator).where("LOWER(first_name) = LOWER(?) OR LOWER(last_name) = LOWER(?)", str, str)
  }

  def title
    item.try(:name) || item_relation.try(:name)
  end

  delegate :accession_no, :thumbnail, :wwqi_url, to: :item, allow_nil: true

  default_scope order('created_at DESC')

  after_create do |contribution|
    if ENV['ADMIN_NOTIFICATION_EMAIL']
      AdminNotificationMailer.new_contribution(contribution).deliver
    end
  end
end

app/controllers/contributions_controller.rb
class ContributionsController < ApplicationController
  inherit_resources
  respond_to :html
  before_filter :custom_authenticate_user!, except: [:index, :show]
  helper_method :selected_item

  def selected_item
    @selected_item ||= if params[:item]
      Item.find(params[:item])
    elsif params[:accession_no]
      Item.find_by_accession_no(params[:accession_no])
    end
  end

  def show
    @contribution = "#{resource.type}Decorator".constantize.decorate(resource)
    show!
  end

  def index
    # List recently created or updated contributions if the reaquest is not from
    # Qajar Women. If so, it responses the request.
    page = params.fetch(:page, 1)
    type = params[:type] ||= 'Transcription'

    @contributions = if selected_item
      Contribution.where(type: type).order('created_at DESC').joins(:item_relation).where('item_relations.accession_no = ?', selected_item.accession_no).page(page).decorate
    else
      Contribution.where(type: type).order('created_at DESC').page(page).decorate
    end

    rpage = params.fetch(:rpage, 1)

    @requests = ContributionRequest.where('details = ? ', type).page(rpage)
  end

  def new
    @contribution = "#{params[:type]}".titleize.constantize.new

    if params[:person_id]
      @contribution.person_url = "#{ENV['WWQI_SITE']}/en/people/#{params[:person_id]}.html"
    end

    # if present, render new form with that item;
    # otherwise, just render the normal new form
    if selected_item
      @contribution.build_item_relation({
        url: selected_item.url,
        name: selected_item.name,
        thumbnail: selected_item.thumbnail,
        accession_no: selected_item.accession_no
      })
    else
      @contribution.build_item_relation
    end
  end

  def create
    @contribution = "#{params[:type]}".constantize.new(params["#{params[:type]}".downcase])
    @contribution.creator = current_user
    if @contribution.save
      redirect_to contribution_path(@contribution),
        notice: "Your contribution was successfully submitted."
      return
    else
      render :new
      return
    end
  end

  def edit
    @contribution = Contribution.find(params[:id])
    render :edit
  end

  def update
    @contribution = Contribution.find(params[:id])
    if @contribution.update_attributes(params[resource.type.downcase.to_sym])
      redirect_to contribution_path(@contribution),
        notice: "Your #{resource.type.downcase} was successfully updated."
    else
      render :edit
    end
  end

  private

  def collection
    # see https://github.com/drapergem/draper/issues/468
    # to view the explanation for `decorate(with: nil)`
    @contributions ||= end_of_association_chain.decorate(with: nil)
  end
end

app/views/contributions/_item_fields.html.haml
.nested-fields
  = f.input :url
  .links
    = link_to_remove_association "remove Item URL", f

app/views/contributions/edit.html.haml
.items-index#new-contribution
  %h4= "Edit #{resource.type}"
  .item-image
    .submission-copy
      %p= "Your #{resource.type.downcase} for: "
      %h3
        = resource.title
    = safe_image_tag resource.thumbnail, class: 'img-polaroid'
= simple_form_for resource do |f|
  = f.input :details, label: resource.type, :input_html => { :class => 'wysihtml5' }, placeholder: "Type your #{resource.type.downcase}..."
  .file-upload
    %h3 Additional Documents
    = f.simple_fields_for :uploads do |upload|
      = render 'partials/upload_fields', f: upload
    .links-add
      .icon-plus-circle
      = link_to_add_association 'Add Upload', f, :uploads, class: 'add-file', partial: 'partials/upload_fields'
  .submit-button
    =f.button :submit, "Save changes", class: 'submit-button', id: 'thread-submit-button'

app/views/contributions/index.html.haml
.items-index
  .intro.contributions-intro
    .cf
      .pull-left.en
        %h4 Help us enrich the WWQI archives.
        %p Here are the ways you can contribute.
      .pull-right.fa
        %h4 به غنی تر شدن آرشیو «دنیای زنان در عصر قاجار» کمک کنید
        %p از این راه‌ها می توانید کمک کنید


    %ul.thread-type.btn-group.contributions-nav.cf
      %li{class: "btn #{'active' if params[:type] == "Transcription"} pull-left"}
        = link_to 'Transcribe a document', contributions_path(type: 'Transcription')
        %span.fa-label تایپ اسناد خطی
      %li{class: "btn #{'active' if params[:type] == 'Translation'} pull-left"}
        = link_to 'Translate a document', contributions_path(type: 'Translation')
        %span.fa-label ترجمه اسناد
      %li{class: "btn #{'active' if params[:type] == 'Biography'} pull-left"}
        = link_to 'Write a biography', contributions_path(type: 'Biography')
        %span.fa-label نگارش شرح حال افراد
      %li.btn.pull-left
        = link_to 'Submit a correction', new_correction_path
        %span.fa-label ارسال تصحیح
  #contributions-content

    - unless selected_item
      .contribution-list-title.cf
        %h3.pull-right.fa
          ="#{ 'اسناد خطی پیشنهادی برای تایپ' if params[:type] == 'Transcription' }"
          ="#{ 'اسناد پیشنهادی برای ترجمه' if params[:type] == 'Translation' }"
          ="#{ 'افراد پیشنهادی برای نگارش شرح حال'if params[:type] == 'Biography' }"
        %h3
          ="#{'Items in need of transcription' if params[:type] == 'Transcription'}"
          ="#{'Items in need of translation' if params[:type] == 'Translation'}"
          ="#{'Persons in need of biography' if params[:type] == 'Biography'}"
      #contribution-list
        %p.feed-intro
          = t("contributions.#{params[:type].downcase}.intro")
        %ul.items#selected-items
          - unless @requests.empty?
            - @requests.each do |r|
              %li
                .item-image.pull-left
                  = safe_image_tag r.item.thumbnail
                .item-content.pull-left
                  .item-title
                    = r.title
                .transcribe.btn.pull-right
                  = link_to t("contributions.#{params[:type].downcase}.button"), new_contribution_path(type: params[:type], item: r.item)
            = paginate @requests, param_name: "rpage"
          -else
            %p= "No items in need of #{params[:type]}"
            %br
        = link_to "Add New", new_contribution_path(type: params[:type]), class: 'btn'

    .contribution-list-title
      %h3.pull-right.fa
        = "#{ 'اسنادی که به تازگی تایپ شده'if params[:type] == 'Transcription' }"
        = "#{'اسنادی که به تازگی ترجمه شده' if params[:type] == 'Translation'}"
        = "#{'شرح حال‌هایی که به تازگی نوشته‌شده' if params[:type] == 'Biography'}"
      %h3
        = "Recently contributed #{params[:type].pluralize}"
        - if selected_item
          for
          = link_to "#{selected_item.title} (#{selected_item.accession_no})", selected_item.wwqi_url

    #contribution-feed
      %p.feed-intro
        = "Here are some recent #{params[:type].pluralize} contributed by the WWQI users:"

      %ul.items#recent-contributions
        - unless @contributions.empty?
          - @contributions.each do |c|
            %li
              .item-image.pull-left
                = safe_image_tag c.thumbnail
              .item-content.pull-left
                .item-header
                  = c.header
                .item-title
                  = link_to c.title, contribution_path(c)
                .item-comments
                  = c.comments_size
                %p.bullet &bull;
                .item-created
                  = c.created_ago
                - if user_signed_in?
                  .item-follow-btn{ style:  "margin-top: -10px;" }
                    - following = current_user.following?(c.object)
                    = link_to following ? 'Unfollow' : 'Follow', '#', :class => ['btn', 'btn-primary', following && 'followed'], :data => { followable_id: c.id, followable_type: c.model.class.to_s.downcase, follow_id: following.try(:id) }
          = paginate @contributions
        - else
          %p No recent contributions

app/views/contributions/new.html.haml
.items-index#new-contribution
  %h4= "New #{resource.type}"
  - if resource.item_relation.try(:accession_no)
    .item-image
      .submission-copy
        %p= "You are submitting a  #{resource.type.downcase} for:"
        %h3= resource.title
      = safe_image_tag resource.item_relation.thumbnail
  - if resource.person_url
    .item-image
      .submission-copy
        %h4= link_to "#{params[:name].titleize}", resource.person_url if params[:name]
      = safe_image_tag "#{ENV['WWQI_PERSON_THUMBNAIL']}/person_#{params[:person_id]}.jpg"

= simple_form_for resource, url: contributions_path(type: resource.type) do |f|
  - if resource.type == 'Biography'
    = f.input :person_name, label: 'Person Name', input_html: { value: params[:name] ? params[:name].titleize : '' }
    = f.input :person_url, label: 'Person URL', input_html: { value: resource.person_url }, placeholder: "e.g. #{ENV['WWQI_SITE']}/en/people/107.html"
  - if resource.item_relation.try(:accession_no)
    = f.simple_fields_for :item_relation do |i|
      .item-group
        = i.input :url, as: :hidden, input_html: { value: resource.item_relation.url}
        = i.input :name, as: :hidden, input_html: { value: resource.item_relation.name }
        = i.input :thumbnail, as: :hidden, input_html: { value: resource.item_relation.thumbnail }
        = i.input :accession_no, as: :hidden, input_html: { value: resource.item_relation.accession_no }
        = i.input :search, as: :hidden, input_html: { value: resource.item_relation.search }
  - elsif resource.type != 'Biography'
    #items.visible
      = f.simple_fields_for :item_relation do |item|
        .item-group
          .input
            = item.input :search, label: 'Search by name or item number', placeholder: 'e.g. tin or 1266A16'
          = item.input :url, :as => :hidden
          = item.input :thumbnail, :as => :hidden
          = item.input :accession_no, :as => :hidden
          = item.input :name, :as => :hidden
          .item-image.pull-left
  = f.input :details, label: resource.type, :input_html => { :class => 'wysihtml5' }, placeholder: "Type your #{resource.type.downcase}..."
  .file-upload
    %p Additional Documents
    = f.simple_fields_for :uploads do |upload|
      = render 'partials/upload_fields', f: upload
    .links-add
      .icon-plus-circle
      = link_to_add_association 'Add Upload', f, :uploads, class: 'add-file', partial: 'partials/upload_fields'
  .submit-button
    = f.button :submit, "Submit #{resource.type}", class: 'submit-button', id: 'thread-submit-button'

= render 'partials/item_autocomplete'

app/views/contributions/show.html.haml
.show
  .item-show.span8.pull-left
    .show-intro
      .item-image.pull-left
        = link_to resource.wwqi_url, target: '_blank' do
          = safe_image_tag resource.thumbnail
      .item-created.pull-left
        = "#{resource.created_ago}, #{resource.header}"
    .item-title
      = link_to resource.title, resource.wwqi_url, target: '_blank'
    .item-details
      .wysiwyg
        != resource.details
  - unless resource.uploads.empty?
    .item-attachments
      %h3 Attached Documents
      %ul.item-uploads
        - resource.uploads.each do |upload|
          %li.item-upload
            %i.icon-file-alt
            = link_to upload[:content], upload.content_url
  = render 'partials/comments', resource: resource