config/routes.rb
WwqiPlatform::Application.routes.draw do
  #devise_for :admin_users, ActiveAdmin::Devise.config
  get "autocomplete/users"

  get '/activity/activity_data'

  devise_for :users, controllers: { registrations: 'registrations' }
  devise_scope :user do
    get '/users/sign_up/:token' => 'registrations#new'
  end

  resources :users do
    resources :notifications
  end

  resources :posts, controller: :threads, path: :threads do
    resources :comments
    resources :followings
  end

  resources :researches do
    resources :comments
    resources :followings
  end

  resources :contributions do
    resources :comments
    resources :followings
  end

  resources :corrections

  resources :biographies

  resources :transcriptions, :translations, controller: :contributions

  match "/admin" => "admin/dashboard#index"
  match "/me" => "profile#show", :as => 'my_profile'
  match "/me/notifications" => "profile#notifications", :as => 'my_notifications'

  root :to => 'site#index'

  ActiveAdmin.routes(self)
end

app/views/layouts/application.html.haml
!!! 5
%html{:lang => "en"}
  %head
    %title WWQI Platform
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    %script{:src => "//use.typekit.net/bwh1aah.js", :type => "text/javascript"}
    %meta{ name: 'viewport', content: 'width=device-width, minimum-scale=1.0, maximum-scale=1.0' }
    %meta{ 'http-equiv' => 'X-UA-Compatible', :content => 'IE=edge,chrome=1' }
    %meta{name: 'apple-mobile-web-app-capable', content: 'yes'}
    - if AJAX_STUB_MODE
      = javascript_include_tag 'jquery.mockjax.js'
      = javascript_include_tag 'wwqi-search-mock'
    :javascript
      try{Typekit.load();}catch(e){}
      window.search_url = '#{SEARCH_URL}';
      window.search_auth = btoa('#{SEARCH_AUTH}');
  %body
    #root
      #header-wrapper
        .container
          #header.row
            #logo-container.span2.pull-left
              = link_to root_path do
                #logo-img
            #title.span5.pull-left
              = link_to root_path do
                %h1 Women&rsquo;s Worlds
                %h2 in Qajar Iran
            #sign-in-nav.pull-right
              %a.icon-menu.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
              .nav-collapse.collapse.nav
                %ul.pull-right
                  %li
                    = link_to 'http://www.qajarwomen.org/en/index.html', target: 'blank' do
                      %h2 WWQI Archive
                      .fa-label آرشیو
                  %li#bullet.hidden-phone.hidden-tablet
                    %h2 &#124;
                  - if current_user && current_user.is_admin?
                    %li
                      = link_to admin_root_path do
                        %h2 Admin Panel
                    %li#bullet.hidden-phone.hidden-tablet
                      %h2 &#124;
                  - unless user_signed_in?
                    %li#scroll-to-registration
                      = link_to(root_path(anchor: 'registration')) do
                        %h2 Sign up
                    %li#scroll-to-sign-in
                      = link_to(root_path(anchor: 'sign-in')) do
                        %h2 Sign in
                        .fa-label ورود
                  - else
                    %li
                      = link_to destroy_user_session_path, method: :delete do
                        %h2 Sign out
                        .fa-label خروج
      #main-nav-wrapper
        .container
          .row
            #main-nav
              #nav.span8.offset2.pull-left
                %ul.nav
                  = nav_link 'Questions & Discussions', posts_path, 'threads', 'پرسش و گفتگو'
                  = nav_link 'Research-in-Progress', researches_path, 'researches', 'پژوهشهای در جریان'
                  = nav_link 'Contributions', contributions_path, ['contributions', 'corrections'], 'مشارکت'
              - if user_signed_in?
                #notifications-outer-wrapper
                  #notifications-inner-wrapper
                    = link_to 'My Profile', my_profile_path, { :class => "pull-right" }
                    .dropdown.pull-right
                      %a.dropdown-toggle{:"data-toggle" => "dropdown", role: "button"}
                        #notifications.pull-right
                          .icon-notification
                          .notification-count
                            %p= current_user.unread_notifications.size
                      %ul.dropdown-menu{role: "menu", "aria-labeledby" => "dLabel"}
                        %li
                          %p Notifications
                        - if current_user.unread_notifications.present?
                          - current_user.unread_notifications.each do |n|
                            %li
                              %p= n.link
                        - else
                          %li
                            %p You have no notifications
                    .fa-label
                      پوشه من
      #main-content
        .container
          = flash_messages
          .content
            = yield
        #root_footer
      = render "partials/footer"